<?php
return  [
    'city' => [
        'Banteay Meanchey',
        'Battambang',
        'Kampong Cham',
        'Kampong Chhnang',
        'Kampong Speu',
        'Kampong Thom',
        'Kampot',
        'Kandal',
        'Koh Kong',
        'Kratié',
        'Mondulkiri',
        'Phnom Penh',
        'Preah Vihear',
        'Prey Veng',
        'Pursat',
        'Ratanak Kiri',
        'Siem Reap',
        'Preah Sihanouk',
        'Steung Treng',
        'Svay Rieng',
        'Takéo',
        'Oddar Meanchey',
        'Kep',
        'Pailin',
        'Tboung Khmum'
    ],
    'team_size' => [
        '1-10',
        '10-30',
        '30-50',
        '50-70',
        '70-100',
        '100+'
    ],
    'education_level' => [
        'Associate Degree',
        'Bachelor Degree',
        'Master Degree',
        'Phd Degree',
        'Doctoral Degree'
    ],
    'career_level' => [
        'Undergraduate',
        'Fresh Graduate',
        'Junior',
        'Senior',
        'Supervisor or Manager',
        'Executive'
    ],
    'industry' => [
       'Accounting',
       'Administration And Office Support',
       'Advertising Arts And Media',
       'Banking And Financial Services',
       'Call Center And Customer Service',
       'Community Services And Development',
       'Construction',
       'Consulting And Strategy',
       'Design And Architecture',
       'Driver',
       'Education And Training',
       'Engineering',
       'Executive',
       'Financial',
       'Food And Beverage',
       'Healthcare And Medical',
       'Hospitality And Tourism',
       'Human Resources And Recruitment',
       'Information Technology',
       'Insurance',
       'Legal',
       'Manufacturing Transport And Logistics',
       'Marketing And Communications',
       'Other',
       'Process Clearing House',
       'Real Estate And Property',
       'Retail And Consumer Products',
       'Sales',
       'Trades And Services'
    ],
    'categories' => [
        'Accounting', 
        'Administration', 
        'Architecture / Engineering',    
        'Assistant / Secretary',
        'Audit / Taxation',
        'Call Center', 
        'Cashier / Service / Barista',
        'Consultancy', 
        'Cook / Clean / Housekeeping',
        'Credit Administration', 
        'Credit Officer / Lending', 
        'Customer Service/Receptionist',
        'Design / Interior / Exterior',
        'Driver / Secrurity', 
        'Electrician / Mechanism', 
        'Finance', 
        'Fresh Graduated',
        'Front Office / Hospitality', 
        'Hight School',
        'HSEQ',
        'Human Resource', 
        'Information Technology / Networking / Infrastructure', 
        'Legal & Compliance', 
        'Logistic / Shipping', 
        'Management', 
        'Marketing', 
        'Medical / Health / Nurse',
        'Operation', 
        'Others',
        'Procurement / Purchasing', 
        'Programmer / Coding / Developer',
        'Project Management',
        'Property Valuator', 
        'QA / QC',
        'Resturant / Captain',
        'Risk & Compliance', 
        'Sale',
        'Sale & Marketing', 
        'Sale Engineer',
        'Security Operation / Safety',
        'Site Engineer', 
        'Stock Controller / Warehouse', 
        'Technician / Maintenance', 
        'Ticketing / Tour / Travel',
        'Traing / Education', 
        'Translation', 
        'Undergraduation', 
        'Video Editor' 
    ],
    'job_type' => [
        'Full Time',
        'Part Time',
        'Internship',
        'Freelance',
        'Temporary',
        'Volunteer'
    ],
    'years_of_experience' => [
        '1 year <',
        '1-2 years',
        '2-3 years',
        '3-4 years',
        '4-5 years',
        '5-7 years',
        '7-9 years',
        '9-12 year',
        '12-15 year',
        '15+ years'
    ]
]
?>